#设置端口号
server:
  port: 8443
  #设置cookie
  servlet:
    session:
      cookie:
        secure: true
        same-site: NONE

#连接数据库
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://127.0.0.1:8888/zsy
    username: root
    password: 1132
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置邮箱
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 2295158461@qq.com
    password: kosrkltdxyopeaad
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    #配置文件
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 215MB



#配置MyBatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: package com.libraryms.pojo
  configuration:
    map-underscore-to-camel-case: true


